### ISSUE TITLE
Implement AssertJ representation

### ISSUE THREAD

**Issue by gatesn** [palantir/safe-logging#37]
I've submitted two PRs, not sure which approach is preferred. In both cases, an exception message for matching against the wrong type of Arg goes from:

```
java.lang.AssertionError: 
Expecting:
 <[test, version]>
to contain:
 <[test, version]>
but could not find:
 <[test]>
```

to

```
java.lang.AssertionError: 
Expecting:
 <[SafeArg[id=test], SafeArg[version=version]]>
to contain:
 <[UnsafeArg[id=test], SafeArg[version=version]]>
but could not find:
 <[UnsafeArg[id=test]]>
```

Happy to add tests to whichever approach is considered better.

**Comment by iamdanfox** [comment]
They're both a bit magic, but super valuable!  Personally I slightly prefer the META-INF one because it seems like a single canonical implementation, whereas the `static{}` block is kinda arbitrary as to which class it should be attached to...

A couple of unit tests would be great and then we can get this merged and released :)
